linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - govet  
    - unused
    - misspell
    - bodyclose
    - nakedret
    - prealloc
    - whitespace
  disable:
    - errcheck
    - golint  
    - interfacer  
    - maligned  

issues:
  exclude-dirs:  
    - bin
    - docs

run:
  timeout: 3m  
  modules-download-mode: readonly
  tests: true