linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - govet
    - unused
    - misspell
    - bodyclose
    - nakedret
    - prealloc
    - whitespace
    - revive
  disable:
    - errcheck
    - golint
    - interfacer
    - maligned

issues:
  exclude-dirs:
    - bin
    - docs
    - vendor
  exclude-files:  
    - ".*\\.test\\.go$"

run:
  timeout: 3m
  modules-download-mode: readonly
  tests: true